services:
  face-recognition:
    build: .
    image: face-recognition:latest
    container_name: face-recognition
    entrypoint: ["python", "-u", "-m", "face_recognition"]
    environment:
      - PYTHONPATH=/app
      - QT_QPA_PLATFORM=offscreen
    volumes:
      - .:/app
      - ./.insightface:/root/.insightface
      - ./.face_recognition:/root/.face_recognition
      - ./workspace:/workspace
    devices:
      - /dev/video0
      - /dev/video1
      - /dev/video2
      - /dev/video3
      - /dev/video4
      - /dev/video5
      - /dev/video6
      - /dev/video7
      - /dev/video8
      - /dev/video9
